use crate::{define_function, define_typeof, wrappers::system::{system_array::SystemArray, system_delegate::Delegate, system_exception::Exception, system_reflection::{MethodInfo, Module, SystemType}, system_string::SystemString, NetObject, SystemObject}};

pub struct Marshal { }

define_typeof!(Marshal, "System.Runtime.InteropServices.Marshal");

impl Marshal {
    // Virtual functions

    // Non-Virtual functions
    define_function!(pub offset_of, 26, isize, t : *mut NetObject<SystemType>, field_name : *mut NetObject<SystemString>);
    define_function!(pub get_last_p_invoke_error, 36, i32);
    define_function!(pub set_last_p_invoke_error, 37, (), error : i32);
    define_function!(pub get_exception_pointers, 40, isize);
    define_function!(pub get_exception_code, 41, i32);
    define_function!(pub structure_to_ptr, 42, (), structure : *mut NetObject<SystemObject>, ptr : isize, f_delete_old : bool);
    define_function!(pub destroy_structure, 44, (), ptr : isize, structuretype : *mut NetObject<SystemType>);
    define_function!(pub get_hinstance, 48, isize, m : *mut NetObject<Module>);
    define_function!(pub get_hr_for_exception, 51, i32, e : *mut NetObject<Exception>);
    //define_function!(pub get_type_info_name, 52, *mut NetObject<SystemString>, type_info : *mut NetObject<ITypeInfo>);
    define_function!(pub get_i_unknown_for_object, 55, isize, o : *mut NetObject<SystemObject>);
    define_function!(pub get_i_dispatch_for_object, 57, isize, o : *mut NetObject<SystemObject>);
    define_function!(pub get_com_interface_for_object, 59, isize, o : *mut NetObject<SystemObject>, t : *mut NetObject<SystemType>);
    //define_function!(pub get_com_interface_for_object, 7, isize, o : *mut NetObject<T>);
    //define_function!(pub get_com_interface_for_object, 60, isize, o : *mut NetObject<SystemObject>, t : *mut NetObject<SystemType>, mode : CustomQueryInterfaceMode);
    define_function!(pub get_object_for_i_unknown, 62, *mut NetObject<SystemObject>, p_unk : isize);
    define_function!(pub get_unique_object_for_i_unknown, 64, *mut NetObject<SystemObject>, unknown : isize);
    define_function!(pub get_typed_object_for_i_unknown, 66, *mut NetObject<SystemObject>, p_unk : isize, t : *mut NetObject<SystemType>);
    define_function!(pub create_aggregated_object, 67, isize, p_outer : isize, o : *mut NetObject<SystemObject>);
    define_function!(pub cleanup_unused_objects_in_current_context, 69, ());
    define_function!(pub are_com_objects_available_for_cleanup, 70, bool);
    define_function!(pub is_com_object, 71, bool, o : *mut NetObject<SystemObject>);
    define_function!(pub release_com_object, 72, i32, o : *mut NetObject<SystemObject>);
    define_function!(pub final_release_com_object, 74, i32, o : *mut NetObject<SystemObject>);
    define_function!(pub get_com_object_data, 76, *mut NetObject<SystemObject>, obj : *mut NetObject<SystemObject>, key : *mut NetObject<SystemObject>);
    define_function!(pub set_com_object_data, 77, bool, obj : *mut NetObject<SystemObject>, key : *mut NetObject<SystemObject>, data : *mut NetObject<SystemObject>);
    define_function!(pub create_wrapper_of_type, 78, *mut NetObject<SystemObject>, o : *mut NetObject<SystemObject>, t : *mut NetObject<SystemType>);
    //define_function!(pub create_wrapper_of_type, 9, *mut NetObject<TWrapper>, o : *mut NetObject<T>);
    define_function!(pub is_type_visible_from_com, 80, bool, t : *mut NetObject<SystemType>);
    define_function!(pub get_native_variant_for_object, 81, (), obj : *mut NetObject<SystemObject>, p_dst_native_variant : isize);
    //define_function!(pub get_native_variant_for_object, 10, (), obj : *mut NetObject<T>, p_dst_native_variant : isize);
    define_function!(pub get_object_for_native_variant, 83, *mut NetObject<SystemObject>, p_src_native_variant : isize);
    //define_function!(pub get_object_for_native_variant, 11, *mut NetObject<T>, p_src_native_variant : isize);
    define_function!(pub get_objects_for_native_variants, 85, *mut NetObject<SystemArray<*mut NetObject<SystemObject>>>, a_src_native_variant : isize, c_vars : i32);
    //define_function!(pub get_objects_for_native_variants, 12, *mut NetObject<SystemArray<*mut NetObject<T>>>, a_src_native_variant : isize, c_vars : i32);
    define_function!(pub get_start_com_slot, 87, i32, t : *mut NetObject<SystemType>);
    define_function!(pub get_end_com_slot, 88, i32, t : *mut NetObject<SystemType>);
    define_function!(pub bind_to_moniker, 89, *mut NetObject<SystemObject>, moniker_name : *mut NetObject<SystemString>);
    define_function!(pub change_wrapper_handle_strength, 93, (), otp : *mut NetObject<SystemObject>, f_is_weak : bool);
    define_function!(pub alloc_h_global, 96, isize, cb : i32);
    define_function!(pub ptr_to_string_ansi, 97, *mut NetObject<SystemString>, ptr : isize);
    define_function!(pub ptr_to_string_ansi_with_len, 98, *mut NetObject<SystemString>, ptr : isize, len : i32);
    define_function!(pub ptr_to_string_uni, 99, *mut NetObject<SystemString>, ptr : isize);
    define_function!(pub ptr_to_string_uni_with_len, 100, *mut NetObject<SystemString>, ptr : isize, len : i32);
    define_function!(pub ptr_to_string_utf8, 101, *mut NetObject<SystemString>, ptr : isize);
    define_function!(pub ptr_to_string_utf8_with_len, 102, *mut NetObject<SystemString>, ptr : isize, byte_len : i32);
    define_function!(pub size_of_struct, 103, i32, structure : *mut NetObject<SystemObject>);
    //define_function!(pub size_of, 13, i32, structure : *mut NetObject<T>);
    define_function!(pub size_of_type, 104, i32, t : *mut NetObject<SystemType>);
    //define_function!(pub query_interface, 105, i32, p_unk : isize, iid : *mut Guid, ppv : *mut isize);
    define_function!(pub add_ref, 106, i32, p_unk : isize);
    define_function!(pub release, 107, i32, p_unk : isize);
    define_function!(pub unsafe_addr_of_pinned_array_element, 108, isize, arr : *mut NetObject<SystemArray<()>>, index : i32);
    //define_function!(pub unsafe_addr_of_pinned_array_element, 15, isize, arr : *mut NetObject<SystemArray<*mut NetObject<T>>>, index : i32);
    define_function!(pub copy_1, 109, (), source : *mut NetObject<SystemArray<i32>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_2, 110, (), source : *mut NetObject<SystemArray<u16>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_3, 111, (), source : *mut NetObject<SystemArray<i16>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_4, 112, (), source : *mut NetObject<SystemArray<i64>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_5, 113, (), source : *mut NetObject<SystemArray<f32>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_6, 114, (), source : *mut NetObject<SystemArray<f64>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_7, 115, (), source : *mut NetObject<SystemArray<u8>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_8, 116, (), source : *mut NetObject<SystemArray<isize>>, start_index : i32, destination : isize, length : i32);
    define_function!(pub copy_9, 117, (), source : isize, destination : *mut NetObject<SystemArray<i32>>, start_index : i32, length : i32);
    define_function!(pub copy_10, 118, (), source : isize, destination : *mut NetObject<SystemArray<u16>>, start_index : i32, length : i32);
    define_function!(pub copy_11, 119, (), source : isize, destination : *mut NetObject<SystemArray<i16>>, start_index : i32, length : i32);
    define_function!(pub copy_12, 120, (), source : isize, destination : *mut NetObject<SystemArray<i64>>, start_index : i32, length : i32);
    define_function!(pub copy_13, 121, (), source : isize, destination : *mut NetObject<SystemArray<f32>>, start_index : i32, length : i32);
    define_function!(pub copy_14, 122, (), source : isize, destination : *mut NetObject<SystemArray<f64>>, start_index : i32, length : i32);
    define_function!(pub copy_15, 123, (), source : isize, destination : *mut NetObject<SystemArray<u8>>, start_index : i32, length : i32);
    define_function!(pub copy_16, 124, (), source : isize, destination : *mut NetObject<SystemArray<isize>>, start_index : i32, length : i32);
    define_function!(pub read_byte_with_offset, 125, u8, ptr : isize, ofs : i32);
    define_function!(pub read_byte, 126, u8, ptr : isize);
    define_function!(pub read_int16_with_offset, 127, i16, ptr : isize, ofs : i32);
    define_function!(pub read_int16, 128, i16, ptr : isize);
    define_function!(pub read_int32_with_offset, 129, i32, ptr : isize, ofs : i32);
    define_function!(pub read_int32, 130, i32, ptr : isize);
    define_function!(pub read_int_ptr_o_with_offset, 131, isize, ptr : *mut NetObject<SystemObject>, ofs : i32);
    define_function!(pub read_int_ptr_with_offset, 132, isize, ptr : isize, ofs : i32);
    define_function!(pub read_int_ptr, 133, isize, ptr : isize);
    define_function!(pub read_int64_with_offset, 134, i64, ptr : isize, ofs : i32);
    define_function!(pub read_int64, 135, i64, ptr : isize);
    define_function!(pub write_byte_with_offset, 136, (), ptr : isize, ofs : i32, val : u8);
    define_function!(pub write_byte, 137, (), ptr : isize, val : u8);
    define_function!(pub write_int16_with_offset, 138, (), ptr : isize, ofs : i32, val : i16);
    define_function!(pub write_int16, 139, (), ptr : isize, val : i16);
    define_function!(pub write_uint16_with_offset, 140, (), ptr : isize, ofs : i32, val : u16);
    define_function!(pub write_uint16, 142, (), ptr : isize, val : u16);
    define_function!(pub write_int32_with_offset, 143, (), ptr : isize, ofs : i32, val : i32);
    define_function!(pub write_int32, 144, (), ptr : isize, val : i32);
    define_function!(pub write_int_ptr_with_offset, 145, (), ptr : isize, ofs : i32, val : isize);
    define_function!(pub write_int_ptr, 147, (), ptr : isize, val : isize);
    define_function!(pub write_int64_with_offset, 148, (), ptr : isize, ofs : i32, val : i64);
    define_function!(pub write_int64, 149, (), ptr : isize, val : i64);
    define_function!(pub prelink, 150, (), m : *mut NetObject<MethodInfo>);
    define_function!(pub prelink_all, 151, (), c : *mut NetObject<SystemType>);
    define_function!(pub get_exception_for_hr, 154, *mut NetObject<Exception>, error_code : i32);
    define_function!(pub get_exception_for_hr_with_info, 155, *mut NetObject<Exception>, error_code : i32, error_info : isize);
    define_function!(pub throw_exception_for_hr, 156, (), error_code : i32);
    define_function!(pub throw_exception_for_hr_with_info, 157, (), error_code : i32, error_info : isize);
    define_function!(pub string_to_h_global_ansi, 163, isize, s : *mut NetObject<SystemString>);
    define_function!(pub string_to_h_global_uni, 164, isize, s : *mut NetObject<SystemString>);
    define_function!(pub string_to_co_task_mem_uni, 165, isize, s : *mut NetObject<SystemString>);
    define_function!(pub string_to_co_task_mem_utf8, 166, isize, s : *mut NetObject<SystemString>);
    define_function!(pub string_to_co_task_mem_ansi, 167, isize, s : *mut NetObject<SystemString>);
    //define_function!(pub generate_guid_for_type, 168, Guid, type : *mut NetObject<SystemType>);
    define_function!(pub generate_prog_id_for_type, 169, *mut NetObject<SystemString>, tape : *mut NetObject<SystemType>);
    define_function!(pub get_delegate_for_function_pointer, 170, *mut NetObject<Delegate>, ptr : isize, t : *mut NetObject<SystemType>);
    define_function!(pub get_function_pointer_for_delegate, 171, isize, d : *mut NetObject<Delegate>);
    define_function!(pub get_hr_for_last_win32_error, 172, i32);
    define_function!(pub zero_free_bstr, 173, (), s : isize);
    define_function!(pub zero_free_co_task_mem_ansi, 174, (), s : isize);
    define_function!(pub zero_free_co_task_mem_unicode, 175, (), s : isize);
    define_function!(pub zero_free_co_task_mem_utf8, 176, (), s : isize);
    define_function!(pub zero_free_global_alloc_ansi, 177, (), s : isize);
    define_function!(pub zero_free_global_alloc_unicode, 178, (), s : isize);
    define_function!(pub string_to_bstr, 179, isize, s : *mut NetObject<SystemString>);
    define_function!(pub ptr_to_string_bstr, 180, *mut NetObject<SystemString>, ptr : isize);
    define_function!(pub get_last_win32_error, 184, i32);
    define_function!(pub get_last_p_invoke_error_message, 185, *mut NetObject<SystemString>);
    define_function!(pub ptr_to_string_auto_with_len, 186, *mut NetObject<SystemString>, ptr : isize, len : i32);
    define_function!(pub ptr_to_string_auto, 187, *mut NetObject<SystemString>, ptr : isize);
    define_function!(pub string_to_h_global_auto, 188, isize, s : *mut NetObject<SystemString>);
    define_function!(pub string_to_co_task_mem_auto, 189, isize, s : *mut NetObject<SystemString>);
    define_function!(pub alloc_h_global_2, 195, isize, cb : isize);
    define_function!(pub re_alloc_h_global, 197, isize, pv : isize, cb : isize);
    define_function!(pub alloc_co_task_mem, 198, isize, cb : i32);
    define_function!(pub free_co_task_mem, 199, (), ptr : isize);
    define_function!(pub re_alloc_co_task_mem, 200, isize, pv : isize, cb : i32);
    define_function!(pub free_bstr, 203, (), ptr : isize);
    define_function!(pub get_last_system_error, 205, i32);
    define_function!(pub set_last_system_error, 206, (), error : i32);
    define_function!(pub get_p_invoke_error_message, 207, *mut NetObject<SystemString>, error : i32);
}
